<nav class="luga-nav-local col-xs-12 col-sm-6 col-md-3 col-lg-3">
	<ul class="list-group">
		<li class="luga-docs-list-heading list-group-item">Luga Core API</li>
		<li class="list-group-item">
			<a href="../docs/index.htm">luga</a>
		</li>
		<li class="list-group-item">
			<a href="../docs/form.htm">luga.form</a>
		</li>
		<li class="list-group-item">
			<a href="../docs/string.htm">luga.string</a>
		</li>
	</ul>
</nav>