<div class="panel panel-default">
	<div class="panel-heading">About Luga Ajaxform</div>
	<div class="panel-body">
		<p>Ajaxform is a JavaScript library that can turn any HTML &lt;form&gt; into a form that get
			submitted by XHR, without the need to reload the page</p>

		<p>In the background, whenever a form is submitted, Ajaxform intercepts the submission, serializes the
			values of the fields, and then issues an HTTP request to the relevant action page using XHR</p>

		<p>See it <a href="#ajaxform/samples/complete">in action</a>, take a look at the <a
				href="#ajaxform/syntax">syntax reference</a> or check how to get <a
				href="#ajaxform/getting-started">started quickly</a></p>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">History</div>
	<div class="panel-body">
		<p>
			Luga Ajaxform evolved out of <a href="http://www.massimocorner.com/libraries/ajaxform/">TMT
			Ajaxform</a>, an XHTML-centric library originally written in 2005. While the design principles are
			pretty much the same and the syntax is similar, the implementation is quite different
		</p>

		<p>
			Unlike the older library, Luga Ajaxform takes advantage of jQuery and it's distributed under an open
			source license
		</p>
	</div>
</div>