<div class="panel panel-default">
	<div class="panel-heading">Syntax reference</div>
	<div class="panel-body">
		<p>The complete syntax reference for HTML5 custom data attributes is included below</p>
	</div>
</div>

<div class="panel panel-default">
	<table class="table table-bordered luga-docs-attributes">
		<th>Attribute</th>
		<th>Description</th>
		<tr>
			<td>data-lugajax-form</td>
			<td>
				Required. Set it to true in order to submit the form using XHR
			</td>
		</tr>
		<tr>
			<td>data-lugajax-action</td>
			<td>
				Optional. URL to where the form will be send.
				If not specified, the value inside the form's action attribute will be used.
			</td>
		</tr>
		<tr>
			<td>data-lugajax-method</td>
			<td>
				Optional. HTTP's method to be used.
				If not specified, the value inside the form's method attribute will be used.
			</td>
		</tr>
		<tr>
			<td>data-lugajax-timeout</td>
			<td>
				Optional. Timeout to be used during the HTTP call (milliseconds). Default to 30000
			</td>
		</tr>
		<tr>
			<td>data-lugajax-success</td>
			<td>
				Optional. Name of the function to be invoked if the form is successfully submitted. Default to
				luga.ajaxform.handlers.replaceForm.
				<a href="#ajaxform/samples/success-handler">See sample</a>
			</td>
		</tr>
		<tr>
			<td>data-lugajax-error</td>
			<td>
				Optional. Name of the function to be invoked if the HTTP call failed. Default to
				luga.ajaxform.handlers.errorAlert.
				<a href="#ajaxform/samples/error-handler">See sample</a>
			</td>
		</tr>
		<tr>
			<td>data-lugajax-successmsg</td>
			<td>
				Optional. Message that will be displayed to the user if the form is successfully submitted. Default to
				"Thanks for submitting the form"
			</td>
		</tr>
		<tr>
			<td>data-lugajax-errormsg</td>
			<td>
				Optional. Message that will be displayed to the user if the HTTP call failed. Default to "Failed to
				submit the form"
			</td>
		</tr>
		<tr>
			<td>data-lugajax-before</td>
			<td>
				Optional. Name of the function to be invoked before the form is send. Default to null.
				<a href="#ajaxform/samples/before-after">See sample</a>
			</td>
		</tr>
		<tr>
			<td>data-lugajax-after</td>
			<td>
				Optional. Name of the function to be invoked after the form is send. Default to null.
				<a href="#ajaxform/samples/before-after">See sample</a>
			</td>
		</tr>
	</table>
</div>