<div class="panel panel-default">
	<div id="multipleRender" class="panel-heading">Why regions are rendered so often?</div>
	<div class="panel-body">

		<p>
			Region associated with a DataSet may indeed be rendered more often than you would have expected.
			This happens because certain events may change both the data contained inside the DataSet and its state.
			Sometimes instead only the data is changed, like after filtering or sorting, without affecting the state at
			all.
		</p>

		<p>
			Since regions are designed to reflect both the data and the DataSet's state, they may react to changes that
			happens in quick succession.
		</p>

		<p>
			There is no need to worry about this, even on very large amount of data the user experience is not affected.
		</p>

	</div>
</div>

<div class="panel panel-default">
	<div id="noSaveMethod" class="panel-heading">Why DataSets doesn't have a .save() method?</div>
	<div class="panel-body">

		<p>
			Luga Data is designed to be as agnostic as possible regarding the REST endpoints it can consume.
			Unfortunately REST API can be really inconsistent, there is no way to design such functionality without
			enforcing severe constrains on the REST endpoint implementation it would consume.
			If you would like to such functionality you can extend the JavaScript classes and implement a .save() method
			that covers your specific needs.
		</p>

	</div>
</div>