<nav class="luga-nav-local col-xs-12 col-sm-6 col-md-3 col-lg-3">
	<ul class="list-group">
		<li class="luga-docs-list-heading list-group-item">Luga CSI</li>
		<li class="list-group-item">
			<a href="../docs/index.htm">About CSI</a>
		</li>
		<li class="luga-docs-list-heading list-group-item">Samples</li>
		<li class="list-group-item">
			<a href="../samples/basic.htm">Basic include</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/after.htm">After handler</a>
		</li>
	</ul>
</nav>