<nav class="luga-nav-local col-xs-12 col-sm-6 col-md-3 col-lg-3">
	<ul class="list-group">

		<li class="luga-docs-list-heading list-group-item">Luga Ajaxform</li>
		<li class="list-group-item">
			<a href="../docs/index.htm">About Ajaxform</a>
		</li>
		<li class="list-group-item">
			<a href="../docs/getting-started.htm">Getting started</a>
		</li>
		<li class="list-group-item">
			<a href="../docs/syntax.htm">HTML Syntax reference</a>
		</li>

		<li class="luga-docs-list-heading list-group-item">Samples</li>
		<li class="list-group-item">
			<a href="../samples/complete.htm">Complete form</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/success-handler.htm">Success handler</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/error-handler.htm">Error handler</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/before-after.htm">Before/after entry handlers</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/validator.htm">With Luga Validator</a>
		</li>

		<li class="luga-docs-list-heading list-group-item">API</li>
		<li class="list-group-item">
			<a href="../docs/api-syntax.htm">API syntax reference</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/api.htm">JavaScript sample</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/api-json.htm">Send raw JSON</a>
		</li>

	</ul>
</nav>