<nav class="local">
	<h2>Ajaxform</h2>
	<ul>
		<li><a href="../docs/index.htm">About Ajaxform</a></li>
		<li><a href="../docs/getting-started.htm">Getting started</a></li>
		<li><a href="../docs/syntax.htm">Syntax reference</a></li>
	</ul>
	<h2>Samples</h2>
	<ul>
		<li><a href="../samples/complete.htm">Complete form</a></li>
		<li><a href="../samples/success-handler.htm">Success handler</a></li>
		<li><a href="../samples/error-handler.htm">Error handler</a></li>
	</ul>
</nav>