<nav class="luga-nav-local col-xs-12 col-sm-6 col-md-3 col-lg-3">
	<ul class="list-group">

		<li class="luga-docs-list-heading list-group-item">Luga Validator</li>
		<li class="list-group-item">
			<a href="../docs/index.htm">About Validator</a>
		</li>
		<li class="list-group-item">
			<a href="../docs/getting-started.htm">Getting started</a>
		</li>
		<li class="list-group-item">
			<a href="../docs/syntax.htm">HTML Syntax reference</a>
		</li>
		<li class="list-group-item">
			<a href="../docs/syntax.htm">FAQ/troubleshooting</a>
		</li>

		<li class="luga-docs-list-heading list-group-item">Samples</li>
		<li class="list-group-item">
			<a href="../samples/complete.htm">Complete form</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/registration.htm">Registration form</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/date.htm">Date validation</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/checkboxes.htm">Checkboxes</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/radio.htm">Radio buttons</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/select.htm">Drop-down (&lt;select&gt;)</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/conditional-validation.htm">Conditional validation</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/handlers-errorbox.htm">Better error display</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/dom-changes.htm">Alter DOM at run-time</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/html5.htm">HTML 5 field types</a>
		</li>

		<li class="luga-docs-list-heading list-group-item">Extensibility</li>
		<li class="list-group-item">
			<a href="../samples/custom-patterns.htm">Custom patterns</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/custom-date-patterns.htm">Custom date patterns</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/custom-validation.htm">Custom validation rules</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/handlers-custom.htm">Custom handlers</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/custom-error.htm">Custom error handler</a>
		</li>

		<li class="luga-docs-list-heading list-group-item">Bootstrap</li>
		<li class="list-group-item">
			<a href="../samples/bootstrap.htm">Bootstrap integration</a>
		</li>

		<li class="luga-docs-list-heading list-group-item">API</li>
		<li class="list-group-item">
			<a href="../docs/api-syntax.htm">API syntax reference</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/api.htm">JavaScript sample</a>
		</li>

	</ul>
</nav>