<nav class="local">
	<h2>Luga Validator</h2>
	<ul>
		<li><a href="../home/index.htm">About</a></li>
		<li><a href="../home/getting-started.htm">Getting started</a></li>
		<li><a href="../home/syntax.htm">Syntax reference</a></li>
	</ul>
	<h2>Samples</h2>
	<ul>
		<li><a href="../samples/complete.htm">Complete form</a></li>
	</ul>
	<h2>Advanced</h2>
	<ul>
		<li><a href="../samples/handlers-errorbox.htm">Errorbox handler</a></li>
		<li><a href="../samples/handlers-custom.htm">Custom handlers</a></li>
	</ul>
</nav>