<nav class="local">
	<h2>Luga Validator</h2>
	<ul>
		<li><a href="../docs/index.htm">About</a></li>
		<li><a href="../docs/getting-started.htm">Getting started</a></li>
		<li><a href="../docs/syntax.htm">Syntax reference</a></li>
	</ul>
	<h2>Samples</h2>
	<ul>
		<li><a href="../samples/complete.htm">Complete form</a></li>
		<li><a href="../samples/registration.htm">Registration form</a></li>
		<li><a href="../samples/date.htm">Date validation</a></li>
		<li><a href="../samples/checkboxes.htm">Checkboxes</a></li>
		<li><a href="../samples/radio.htm">Radio buttons</a></li>
		<li><a href="../samples/select.htm">Drop-down (&lt;select&gt;)</a></li>
		<li><a href="../samples/conditional-validation.htm">Conditional validation</a></li>
	</ul>
	<h2>Customization</h2>
	<ul>
		<li><a href="../samples/custom-patterns.htm">Custom patterns</a></li>
	</ul>
	<h2>Advanced</h2>
	<ul>
		<li><a href="../samples/handlers-errorbox.htm">Errorbox handler</a></li>
		<li><a href="../samples/handlers-custom.htm">Custom handlers</a></li>
	</ul>
</nav>