<div class="panel panel-default">
	<div class="panel-heading">About Luga Validator</div>
	<div class="panel-body">
		<p>Validator is a JavaScript library for client-side form validation. It was developed with several goals in
			mind:</p>

		<ul class="luga-docs-list">
			<li>Attach validation rules to form fields using HTML5 custom data attributes in a declarative way</li>
			<li>Make code generation painless. Defining the validation rules as attributes of the field tags makes it
				easier to generate forms server-side, or write code generators,
				because the form fields are self-contained
			</li>
			<li>Easy to use out of the box for HTML people, even with minimal programming skills, while still being
				totally open to extensibility by developers familiar with JavaScript
			</li>
			<li>Streamline authoring/editing on any IDE that can provide custom code hints for tags</li>
		</ul>

		<p>See it <a href="#validator/samples/complete">in action</a>, take a look at the <a href="#validator/syntax">syntax
			reference</a> or check how to get <a href="#validator/getting-started">started quickly</a></p>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">Unit test</div>
	<div class="panel-body">
		<p>
			Luga Validator contains a comprehensive set of <a href="../test/SpecRunner.htm?spec=luga.validator">unit
			tests</a>, developed with <a href="https://github.com/jasmine/jasmine">Jasmine</a>
		</p>

		<p>
			The unit tests play a fundamental role in ensuring the code is robust and, at the very same time,
			provide plenty of useful information about the API
		</p>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">History</div>
	<div class="panel-body">
		<p>
			Luga Validator evolved out of <a href="http://www.massimocorner.com/libraries/validator/">TMT Validator</a>,
			an XHTML-centric library originally written in 2005. While the design principles are pretty much the same
			and the syntax is similar, the implementation is quite different.
		</p>

		<p>
			Unlike the older library, Luga Validator takes advantage of jQuery and it's distributed under an open source
			license
		</p>
	</div>
</div>