<script>
	luga.validator.patterns.httpstart = new RegExp("^http://");
</script>

<div class="panel panel-default">
	<div class="panel-heading">Custom patterns</div>
	<div class="panel-body">

		<p>
			Luga Validator was designed with extensibility in mind. That's why all the validation rules and patterns are
			stored inside a JavaScript object.
		</p>

		<p>
			For this custom validation you want to be sure the user enters a string starting with http://. Our regular
			expression is <strong>^http://</strong>
		</p>

		<p>
			Luga Validator stores all patterns inside luga.validator.patterns, a JavaScript object, acting as a
			container for both built-in and custom patterns.
		</p>

		<p>
			So all you need to do is to add the following line of JavaScript code:
		</p>

		<pre><code class="language-javascript">luga.validator.patterns.httpstart = new RegExp("^http://");</code></pre>

		<p>
			The HTML will look like:
		</p>

<pre><code class="language-markup">&lt;input type="text" name="theurl"
	data-lugavalidator-required="true"
	data-lugavalidator-pattern="httpstart"
	data-lugavalidator-message="Please URL!"/&gt;</code></pre>

	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">Enter an URL</div>
	<div class="panel-body">
		<form data-lugavalidator-validate="true">
			<div class="form-group">
				<label for="theurl" class="control-label">Url: (must start with http://)</label>
				<input type="text" class="form-control" name="theurl" id="theurl" value="test"
					   data-lugavalidator-required="true" data-lugavalidator-pattern="httpstart"
					   data-lugavalidator-message="Please URL!"/>
			</div>
			<div class="form-group">
				<input type="submit" value="Submit"/>
			</div>
		</form>
	</div>
</div>