<ul class="list-group">
	<li class="luga-docs-list-heading list-group-item">Luga Common API</li>
	<li class="list-group-item">
		<a href="#common/index">luga</a>
	</li>
	<li class="list-group-item">
		<a href="#common/form">luga.form</a>
	</li>
	<li class="list-group-item">
		<a href="#common/string">luga.string</a>
	</li>
	<li class="list-group-item">
		<a href="#common/localStorage">luga.localStorage</a>
	</li>
	<li class="list-group-item">
		<a href="#common/notifier">luga.Notifier</a>
	</li>
</ul>