<div class="panel panel-default">
	<div class="panel-heading">Better UI for validation</div>
	<div class="panel-body">
		<form data-lugavalidator-validate="true" data-lugavalidator-error="luga.validator.handlers.bootstrap">
			<div class="form-group">
				<label for="age">Age (required, positive integer, min 18, max 75)</label>
				<input type="text" class="form-control" id="age" name="age" value="18"
					   data-lugavalidator-required="true"
					   data-lugavalidator-message="Please insert a valid age"
					   data-lugavalidator-pattern="positiveinteger"
					   data-lugavalidator-minnumber="18"
					   data-lugavalidator-maxnumber="75"
					   data-lugavalidator-filters="numbersonly"/>
			</div>
			<div class="form-group">
				<label for="name" class="control-label">Name (required)</label>
				<input type="text" class="form-control" id="name" name="name"
					   data-lugavalidator-required="true"
					   data-lugavalidator-message="Please insert a name"/>
			</div>
			<div class="form-group">
				<label for="email" class="control-label">Email</label>
				<input type="text" class="form-control" id="email" name="email"
					   data-lugavalidator-required="true"
					   data-lugavalidator-message="Please insert a valid email"
					   data-lugavalidator-email="true"/>
			</div>
			<div class="form-group">
				<label for="date">Date (not required, date, YYYY-MM-DD)</label>
				<input type="text" class="form-control" id="date" name="date" value="2005-05-09"
					   data-lugavalidator-message="Please insert a valid date using the YYYY-MM-DD format"
					   data-lugavalidator-datepattern="YYYY-MM-DD"/>
			</div>
			<div class="form-group">
				<label for="comments">Comments (not required, min 3 chars, max 10)</label>
						<textarea id="comments" class="form-control" name="comments" cols="20" rows="3"
								  data-lugavalidator-message="Comments should be from 3 to 10 chars"
								  data-lugavalidator-minlength="3"
								  data-lugavalidator-maxlength="10">
						</textarea>
			</div>

			<div class="form-group">
				<input type="submit" value="Submit"/>
			</div>
		</form>

	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">Use Bootstrap's validation states</div>
	<div class="panel-body">
		<p>By default the validator uses JavaScript alert boxes to display errors to the user.
			If you want to use Bootstrap's <a href="http://getbootstrap.com/css/#forms-control-validation">validation
				states</a> instead, use "luga.validator.handlers.bootstrap" as error handler.
		</p>

<pre><code class="language-markup">&lt;form data-lugavalidator-validate="true" data-lugavalidator-error="luga.validator.handlers.bootstrap"&gt;
</code></pre>

		<p>The value for the default error handler is stored inside luga.validator.CONST.HANDLERS.FORM_ERROR. You can
			override it the Bootstrap handler:</p>

<pre><code class="language-javascript">luga.validator.CONST.HANDLERS.FORM_ERROR = "luga.validator.handlers.bootstrap";
</code></pre>

	</div>
</div>