<div class="container-fluid">
	<nav class="navbar navbar-default">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
					data-target="#main-navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="../../index.htm">Luga JS</a>
		</div>
		<!-- Everything may toggle -->
		<div class="collapse navbar-collapse" id="main-navbar-collapse">
			<ul class="nav navbar-nav">
				<li><a href="../../core/docs/index.htm">:: Core ::</a></li>
				<li><a href="../../ajaxform/docs/index.htm">:: Ajaxform ::</a></li>
				<li><a href="../../data/docs/index.htm">:: Luga Data::</a></li>
				<li><a href="../../validator/docs/index.htm">:: Validator ::</a></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">More <span
							class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="../../csi/docs/index.htm">CSI</a></li>
						<li role="separator" class="divider"></li>
						<li><a href="https://github.com/MassimoFoti/lugajs">GitHub</a></li>
						<li><a href="../../../archive/luga-js.zip">Download</a></li>
					</ul>
				</li>
			</ul>
		</div>
	</nav>
</div>