<nav class="main">
	<ul>
		<li>
			<a href="../../index.htm" title="Home">Luga JS</a>
		</li>
		<li>
			<a href="../../validator/home/index.htm" title="Client-side form validation">Validator</a>
		</li>
		<li>
			<a href="../../csi/home/index.htm" title="Client-side include">CSI</a>
		</li>
		<!--
		<li>
			<a href="../../dataset/index.htm" title="Store and display data">Dataset</a>
		</li>
		-->
		<li>
			<a href="https://github.com/MassimoFoti/lugajs" title="Se Luga JS on GitHub">GitHub</a>
		</li>
		<li>
			<a href="https://github.com/MassimoFoti/lugajs/archive/master.zip" title="Download zip from GitHub">Download</a>
		</li>
	</ul>
</nav>