<nav class="main">
	<ul>
		<li>
			<a href="../../index.htm" title="Home">Luga JS</a>
		</li>
		<li>
			<a href="../../core/docs/index.htm" title="Core API">Core</a>
		</li>
		<li>
			<a href="../../validator/docs/index.htm" title="Client-side form validation">Validator</a>
		</li>
		<li>
			<a href="../../csi/docs/index.htm" title="Client-side include">CSI</a>
		</li>
		<!--
		<li>
			<a href="../../dataset/index.htm" title="Store and display data">Dataset</a>
		</li>
		-->
		<li>
			<a href="https://github.com/MassimoFoti/lugajs" title="Luga JS on GitHub">GitHub</a>
		</li>
		<li>
			<a href="https://github.com/MassimoFoti/lugajs/raw/master/dist/luga-js.zip" title="Download zip distro">Download</a>
		</li>
	</ul>
</nav>