<nav class="luga-nav-local col-xs-12 col-sm-6 col-md-3 col-lg-3">
	<ul class="list-group">
		<li class="luga-docs-list-heading list-group-item">Luga Data</li>
		<li class="list-group-item">
			<a href="../docs/index.htm">About Luga Data</a>
		</li>
		<li class="luga-docs-list-heading list-group-item">Dataset</li>
		<li class="list-group-item">
			<a href="../samples/databinding-basic.htm">Basic databinding</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/sort.htm">Sorting</a>
		</li>
		<li class="luga-docs-list-heading list-group-item">DetailsSet</li>
		<li class="list-group-item">
			<a href="../samples/master-details.htm">Master-details</a>
		</li>
		<li class="luga-docs-list-heading list-group-item">Region</li>
		<li class="list-group-item">
			<a href="../samples/context-properties.htm">Context properties</a>
		</li>
		<li class="list-group-item">
			<a href="../samples/custom-region-type.htm">Custom templating</a>
		</li>
	</ul>
</nav>