<nav class="luga-nav-local col-xs-12 col-sm-6 col-md-3 col-lg-3">
	<ul class="list-group">

		<li class="luga-docs-list-heading list-group-item">Luga Data</li>
		<li class="list-group-item">
			<a href="../docs/index.htm">About Luga Data</a>
		</li>
		<li class="list-group-item">
			<a href="../docs/notifier.htm">Notifier/Observer</a>
		</li>

		<li class="luga-docs-list-heading list-group-item">Dataset</li>
		<li class="list-group-item">
			<a href="../dataset/databinding-basic.htm">Databinding</a>
		</li>
		<li class="list-group-item">
			<a href="../dataset/sort.htm">Sorting</a>
		</li>
		<li class="list-group-item">
			<a href="../dataset/without-region.htm">Without region</a>
		</li>
		<li class="list-group-item">
			<a href="../dataset/api.htm">API Syntax reference</a>
		</li>

		<li class="luga-docs-list-heading list-group-item">DetailsSet</li>
		<li class="list-group-item">
			<a href="../detailset/master-details.htm">Master-details</a>
		</li>
		<li class="list-group-item">
			<a href="../detailset/api.htm">API Syntax reference</a>
		</li>

		<li class="luga-docs-list-heading list-group-item">Region</li>
		<li class="list-group-item">
			<a href="../region/handlebars.htm">HTML templating</a>
		</li>
		<li class="list-group-item">
			<a href="../region/context.htm">Context data</a>
		</li>
		<li class="list-group-item">
			<a href="../region/traits.htm">Traits</a>
		</li>
		<li class="list-group-item">
			<a href="../region/state.htm">Leverage state</a>
		</li>
		<li class="list-group-item">
			<a href="../region/syntax.htm">HTML syntax reference</a>
		</li>

		<li class="luga-docs-list-heading list-group-item">Extensibility</li>
		<li class="list-group-item">
			<a href="../extensibility/custom-dataset.htm">Custom dataSets</a>
		</li>
		<li class="list-group-item">
			<a href="../extensibility/custom-region-type.htm">Custom regions</a>
		</li>
		<li class="list-group-item">
			<a href="../extensibility/custom-trait.htm">Custom traits</a>
		</li>

	</ul>
</nav>