<nav class="local">
	<h2>Luga Data</h2>
	<ul>
		<li><a href="../docs/index.htm">About</a></li>
	</ul>
	<h2>DataSet</h2>
	<ul>
		<li><a href="../samples/databinding-basic.htm">Basic databinding</a></li>
		<li><a href="../samples/sort.htm">Sorting</a></li>
	</ul>
	<h2>DetailsSet</h2>
	<ul>
		<li><a href="../samples/master-details.htm">Master-details</a></li>
	</ul>
	<h2>Region</h2>
	<ul>
		<li><a href="../samples/context-properties.htm">Context properties</a></li>
		<li><a href="../samples/custom-region-type.htm">Custom templating</a></li>
	</ul>
</nav>